### ISSUE TITLE
R-T3.4-11: The tool must decrease bug-fixing times with respect to manual inspection

### ISSUE THREAD

**Issue by dardin88** [radon-h2020/radon-defect-prediction-api#7]
ID | R-T3.4-11
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | PERFORMANCE_EFFICIENCY
User Story | As an Operations Engineer I want the tool to decrease the time to inspect the infrastructure manually considerably
Requirement | The tool must diminish the time to detect defects with respect to manual inspection by at least 20%
Priority | Must have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | User study with time improved by at least 20%
Dependency |  R-T3.4-10 https://github.com/radon-h2020/radon-defect-prediction-api/issues/5

**Comment by stefanodallapalma** [comment]
@maelstromdat @dardin88 (TDJ) @sdagostini (ENG) @naesheim (PRQ) I think we have to design the industrial case studies keeping in mind this **must-have** requirement.

See also issue #5.

**Comment by stefanodallapalma** [comment]
@gcasale 
Similar to issue #5, this requirement will take time to be addressed. We are designing industrial cases studies with ENG and PRQ to address it.

**Comment by stefanodallapalma** [comment]
Removed.
First, the requirement partially overlaps R-T3.4-10 (#5), which states that the defect-prediction tool must improve performances over manual inspection. Second, the bug-fixing time is a developers’ concern rather than the defect predictor tool and depends on their ability to find a fix for a given bug. As the defect-predictor is essentially a detector, we stick with the requirement R-T3.4-10 to improve the performance in identifying defects during manual inspection.

**Comment by gcasale** [comment]
Closed state approved.
