### ISSUE TITLE
Getting started information

### ISSUE THREAD

**Issue by gcasale** [radon-h2020/radon-defect-prediction-api#8]
I could follow the instructions in the README.md and successfully run the REST call:
http://localhost:5000/api/metrics/**all**

However the other REST call did not work. In both cases, it wasn't clear what the call was doing and how to continue using the tool.

**Comment by stefanodallapalma** [comment]
HI @gcasale,

today I have merged a brand new version in the main branch and updated the README accordingly.
It would be great if you or someone external to TJD tried it.
It now relies on Firebase Database and Storage, therefore the README is mostly about how to configure the project on Firebase rather than use the application.
I believe the GUI is pretty intuitive once you run the server. A further documentation will be available soon and integrated in the web application itself.  

Let me know what do you think!
